name: Super Simple Test
on: [workflow_dispatch]
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Just echo
        run: echo "Runner is working!"
      
      - name: List files
        run: ls -la
